name: Python Cache (Linux)
description: Caches a full installation of Haystack dependencies

inputs:
 pythonPath:
    description: 'Python path to cache/restore'
    required: true
 pythonVersion:
    description: 'Python version to use'
    required: true
    default: 3.7

runs:
  using: "composite"
  steps:

  - name: Print date
    shell: bash
    run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

  - uses: actions/checkout@v2
  - uses: actions/setup-python@v2
    with:
      python-version: ${{ inputs.pythonVersion }}

  - name: Cache
    id: cache-python-env
    uses: actions/cache@v2
    with:
      path: '${{ inputs.pythonPath }}'
      # The cache will be rebuild every day and at every change of the dependency files
      key: linux-py${{ inputs.pythonVersion }}-${{ env.date }}-${{ hashFiles('**/setup.py') }}-${{ hashFiles('**/setup.cfg') }}-${{ hashFiles('**/pyproject.toml') }}

  - name: Install dependencies
    if: steps.cache-python-env.outputs.cache-hit != 'true'
    shell: bash
    run: |
      pip install --upgrade pip
      pip install .[test]
      pip install rest_api/
      pip install ui/
      pip install torch-scatter -f https://data.pyg.org/whl/torch-1.10.0+cpu.html
