name: Checklist

on:
  workflow_dispatch:
  pull_request:


jobs:

  check:
    runs-on: ubuntu-20.04
    timeout-minutes: 45
    steps:

    # - name: Comment PR
    #   uses: thollander/actions-comment-pull-request@v1
    #   with:
    #     message: 'Loading ...'
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    # - name: Wait
    #   run: sleep 10

      
    - name: List workflows
      uses: actions/github-script@v6
      id: available_workflows
      with:
        script: |
          const opts = github.rest.actions.listRepoWorkflows({
            owner,
            repo,
          })
          const workflows = await github.paginate(opts)
          return workflows

# github.rest.actions.createWorkflowDispatch({
#   owner,
#   repo,
#   workflow_id,
#   ref,
# });
# https://octokit.github.io/rest.js/v18#actions-list-repo-workflows
# https://octokit.github.io/rest.js/v18/#actions-list-workflow-runs
# https://octokit.github.io/rest.js/v18#actions-get-workflow
# https://octokit.github.io/rest.js/v18#actions-get-workflow-run


    - name: Edit PR comment
      uses: thollander/actions-comment-pull-request@v1
      with:
        message: 'Available workflows: ${{steps.set-result.outputs.available_workflows}}'
        comment_includes: 'Loaded!'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
