name: Lint

on:
  # Activate this workflow manually
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.png'
      - '**/*.gif'

jobs:

  pylint:
    runs-on: ubuntu-20.04
    timeout-minutes: 45
    steps:

    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v1
      with:
        message: 'Loading ...'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    - uses: actions/checkout@v2

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install Haystack
      run: |
        pip install --upgrade pip
        pip install .[all]
        pip install rest_api/
        pip install ui/

    - name: Pylint
      run: |
        pylint -ry haystack/
        pylint -ry rest_api/
        pylint -ry ui/



    - name: Edit PR comment
      uses: thollander/actions-comment-pull-request@v1
      with:
        message: 'Loaded ! (edited)'
        comment_includes: 'Loading'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}